### ISSUE TITLE
incomplete installation?

### ISSUE THREAD

**Issue by chubukov** [ned2/slapdash#27]
I must be doing something wrong during installation. I set up a virtualenv and then followed all the commands, with defaults when prompted. I can get `run-slapdashed-app-dev` to work fine, but when I try to run `run-slapdashed-app-prod` I get `ModuleNotFoundError: No module named 'slapdash'` (and also mod_wsgi errors). Also, I don't see any reference to `project_slug.wsgi` as mentioned in the docs.

Here's exactly what I did:
```
python3.6 -m venv slap_env
slap_env/bin/python -m pip install cookiecutter
slap_env/bin/cookiecutter https://github.com/ned2/slapdash
slap_env/bin/python -m pip install -e slapdashed_app/
```

**Comment by ned2** [comment]
ah yes, that's my bad. thanks for reporting!

I hadn't updated the prod bash script to use the `{{cookiecutter.project_slug}}` field. That should be fixed now with 1a79a4e64e17bb6f9fbf4666487f9b6c88c2f13d. Can you check and see if it works?

I really need to create some tests for the two run scripts.

**Comment by chubukov** [comment]
Thanks @ned2, that at least got it to run (after I installed mod_wsgi and put it in the path). Though I then got a mod_wsgi error

> AH00526: Syntax error on line 18 of /tmp/mod_wsgi-localhost:8000:100016/httpd.conf:
> Group takes one argument, Effective group id for this server
>
Don't worry too much if it's something specific to my system. I mostly wanted to see how you were setting up the mod_wsgi.

Btw, I still don't follow this line of the readme:

>$ gunicorn project_slug.wsgi
>
This doesn't seem to exist, what should this command look like?

**Comment by ned2** [comment]
Hmmm that error is odd. Looks like mod_wsgi-express is generating an invalid Apache conf. I have no idea why that would be.

project_slug simply refers to the ID you gave your project when creating the project with cookiecutter. So it's just the module name of your project. The default value is `slapdashed_app`. Perhaps I need to make the documentation clearer here.
